spring.application.name=${SPRING_APPLICATION_NAME:honeybodger}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/honeybadger_DB}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:maksoud}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
server.port=${SERVER_PORT:8080}

springdoc.api-docs.path=${SPRINGDOC_API_DOCS_PATH:/api-docs}
springdoc.swagger-ui.path=${SPRINGDOC_SWAGGER_UI_PATH:/swagger-ui.html}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED:true}
springdoc.swagger-ui.operations-sorter=${SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER:method}
springdoc.swagger-ui.tags-sorter=${SPRINGDOC_SWAGGER_UI_TAGS_SORTER:alpha}
